### ISSUE TITLE
notebook: use local input file 

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-worldpopulation#5]
In the initial commit, the original IPython notebook example by @alizeepace was committed "as is" from past tests.  The notebook downloads input file from the web:

- http://inveniosoftware.org/download/invenio-demo-site-files/World_historical_and_predicted_populations_in_percentage.csv

In order to have a more faithful REANA example, it would be good to modify the notebook to use local input file, and perhaps add another one (with absolute population numbers) to demonstrate the analysis reading input data from than one input file.

The IPython notebook should then be changed accordingly.

**Comment by diegodelemos** [comment]
This file should be coming from the seeding step (see https://github.com/reanahub/reana-client/issues/3)
